name = "hugo-theme-eco"
license = "MIT"
licenselink = "https://github.com/XDongG/hugo-theme-eco/blob/main/LICENSE"
description = "A clean, eco-friendly Hugo theme for energy efficiency and environmental professionals"
homepage = "https://github.com/XDongG/hugo-theme-eco"
tags = ["blog", "clean", "eco", "green", "responsive", "dark-mode", "multilingual"]
features = ["blog", "responsive", "dark-mode", "multilingual", "i18n"]
min_version = "0.128.0"

[author]
  name = "Your Name"
  homepage = "https://yourwebsite.com"

[original]
  name = "hugo-theme-eco"
  homepage = "https://github.com/XDongG/hugo-theme-eco"
  repo = "https://github.com/XDongG/hugo-theme-eco"

